=== JoseAlfonsoVivo/tema03/Ej2.dtd
<!ELEMENT minecraftItems (item+)>
    
    <!ELEMENT item (id, name, type, rarity, damage, description, materials?, enchantments?)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT rarity (#PCDATA)>
    <!ELEMENT damage (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    
    <!ELEMENT materials (material+)>
    <!ELEMENT material (#PCDATA)>

    <!ELEMENT enchantments (enchantment+)>
    <!ELEMENT enchantment (#PCDATA)>

    <!ATTLIST item 
        crafteable (true | false) #REQUIRED
        enchantable (true | false) #REQUIRED>

    <!ATTLIST minecraftItems
        lang CDATA #REQUIRED>

=== JoseAlfonsoVivo/tema03/Ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "Ej2.dtd">

<minecraftItems lang="es">

    <item crafteable="true" enchantable="true">
        <id> 1 </id>
        <name> Espada </name>
        <type> Arma </type>
        <rarity> Diamante </rarity>
        <damage> 7 </damage>
        <description> Es el arma principar para luchar que hace mucho daño y es rapida </description>
        <materials>
            <material> 2 diamantes </material>
            <material> 1 palo </material>
        </materials>
        <enchantments>
            <enchantment> Golpeo 5 </enchantment>
            <enchantment> Empuje 2 </enchantment>
            <enchantment> Aspecto ígneo 2 </enchantment>
            <enchantment> Botín 3 </enchantment>
            <enchantment> Filo arrasador 3 </enchantment>
            <enchantment> Reparación </enchantment>
            <enchantment> Irrompibilidad 3 </enchantment>
            <enchantment> Maldición de desaparición </enchantment>
        </enchantments>
    </item>

    <item crafteable="true" enchantable="true">
        <id> 2 </id>
        <name> Pico </name>
        <type> Herramienta </type>
        <rarity> Diamante </rarity>
        <damage> 4 </damage>
        <description> El pico es una de las herramientas más usadas en el juego para excavar todos los minerales y algunos otros tipos de bloques. </description>        <materials>
            <material> 3 diamantes </material>
            <material> 2 palos </material>
        </materials>
        <enchantments>
            <enchantment> Eficiencia 5 </enchantment>
            <enchantment> Fortuna 3 </enchantment>
            <enchantment> Toque de seda </enchantment>
            <enchantment> Irrompibilidad 3 </enchantment>
            <enchantment> Reparación </enchantment>
            <enchantment> Maldición de desaparición </enchantment>
        </enchantments>
    </item>

    <item crafteable="true" enchantable="true">
        <id> 3 </id>
        <name> Hacha </name>
        <type> arma y herramienta </type>
        <rarity> Diamante </rarity>
        <damage> 6 </damage>
        <description> Es tanto arma como herramienta ya que sirve para talar arboles y para luchar (aunque es muy lenta) </description>
        <materials>
            <material> 3 diamantes </material>
            <material> 2 palos </material>
        </materials>
        <enchantments>
            <enchantment> Eficiencia 5 </enchantment>
            <enchantment> Fortuna 3 </enchantment>
            <enchantment> Toque de seda </enchantment>
            <enchantment> Irrompibilidad 3 </enchantment>
            <enchantment> Reparación </enchantment>
            <enchantment> Maldición de desaparición </enchantment>
        </enchantments>
    </item>

</minecraftItems>
