=== JoseAlfonsoVivo/tema03/Ej3.dtd
<!ELEMENT escena (figuras)>
    <!ELEMENT figuras (figura+)>
        <!ELEMENT figura (altura?, ancho?, radio?, posición)>
            <!ATTLIST figura tipo (rectangulo | circunferencia | linea) #REQUIRED>
        <!ELEMENT altura (#PCDATA)>
        <!ELEMENT ancho (#PCDATA)>
        <!ELEMENT radio (#PCDATA)>
        <!ELEMENT posición (x, y)>
            <!ELEMENT x (#PCDATA)>
            <!ELEMENT y (#PCDATA)>

=== JoseAlfonsoVivo/tema03/Ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escena SYSTEM "Ej3.dtd">
<escena>  
    <figuras>
        <figura tipo="rectangulo">
            <altura> 10 </altura>
            <ancho> 20 </ancho>
            <posición>
                <x>100</x>
                <y>150</y>
            </posición>
        </figura>
       <figura tipo="circunferencia">
            <radio> 3 </radio>
            <posición>
                <x>200</x>
                <y>250</y>
            </posición>
       </figura>
       <figura tipo="linea">
            <posición>
                <x>300</x>
                <y>350</y>
            </posición>
       </figura>
    </figuras>
</escena>
