=== JoseAlfonsoVivo/tema03/Ej6.dtd
<!ELEMENT tickets (membretes, sucursales, articulos, ticket*)>
    <!ELEMENT membretes (membrete*)>
        <!ELEMENT membrete EMPTY>
        <!ATTLIST membrete 
            id ID #REQUIRED
            cif CDATA #REQUIRED
            razon_social CDATA #REQUIRED
            direccion CDATA #REQUIRED
            cp CDATA #REQUIRED
            poblacion CDATA #REQUIRED
            telefono CDATA #REQUIRED>
    
    <!ELEMENT sucursales (sucursal*)>
        <!ELEMENT sucursal EMPTY>
        <!ATTLIST sucursal 
            id ID #REQUIRED
            membrete_ref IDREF #REQUIRED
            nombre CDATA #REQUIRED
            direccion CDATA #REQUIRED
            cp_Su CDATA #REQUIRED>
        
    <!ELEMENT articulos (articulo*)>
        <!ELEMENT articulo EMPTY>
        <!ATTLIST articulo 
            codigo ID #REQUIRED
            descripcion CDATA #REQUIRED
            precio CDATA #REQUIRED>
    
    <!ELEMENT ticket (cabecera, lineas, resumen)>
        <!ELEMENT cabecera EMPTY>
        <!ATTLIST cabecera 
            membrete_ref IDREF #REQUIRED
            sucursal_ref IDREF #REQUIRED
            num_ticket CDATA #REQUIRED
            fecha CDATA #REQUIRED
            hora CDATA #REQUIRED
            tpv CDATA #REQUIRED>
        <!ELEMENT lineas (linea*)>
        <!ELEMENT linea EMPTY>
            <!ATTLIST linea 
                cantidad CDATA #REQUIRED
                articulo_ref IDREF #REQUIRED
                importe CDATA #REQUIRED>
        <!ELEMENT resumen EMPTY>
        <!ATTLIST resumen 
            forma_de_pago CDATA #REQUIRED
            total CDATA #REQUIRED>

=== JoseAlfonsoVivo/tema03/Ej6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tickets SYSTEM "Ej6.dtd">

<tickets>

    <membretes>
        <membrete id="Me1" cif="A12345678" razon_social="Empresa X" direccion="Calle X" cp="00000" poblacion="Valencia" telefono="654987321" />
    </membretes>

    <sucursales>
        <sucursal id="Su1" membrete_ref="Me1" nombre="Sucursal X" direccion="Calle_Su X" cp_Su="11111"/>
        <sucursal id="Su2" membrete_ref="Me1" nombre="Sucursal Y" direccion="Calle_Su X" cp_Su="22222"/>
    </sucursales>
    
    <articulos>
        <articulo codigo="A001" descripcion="Platanos" precio="2.50" />
        <articulo codigo="A002" descripcion="Galletas" precio="5.50" />
        <articulo codigo="A003" descripcion="Salmon" precio="20.00" />
        <articulo codigo="B001" descripcion="Queso" precio="3.00" />
        <articulo codigo="B003" descripcion="Zumo de naranja" precio="2.00" />
    </articulos>
    
    <!-- Ticket 1 -->
    <ticket>
        <cabecera  membrete_ref="Me1" sucursal_ref="Su1" num_ticket="100" fecha="20-04-2024" hora="14:00" tpv="¿---?" />
        <lineas>
            <linea cantidad="2" articulo_ref="A001" importe="4.00" />
            <linea cantidad="3" articulo_ref="A002" importe="1.00" />
            <linea cantidad="1" articulo_ref="A003" importe="12.50" />
        </lineas>
        <resumen forma_de_pago="Tarjeta" total="40.00" />
    </ticket>
    
    <!-- Ticket 2 -->
    
    <ticket>
        <cabecera  membrete_ref="Me1" sucursal_ref="Su2" num_ticket="200" fecha="15-06-2024" hora="10:00" tpv="¿---?" />
        <lineas>
            <linea cantidad="1" articulo_ref="B001" importe="3.00" />
            <linea cantidad="2" articulo_ref="A002" importe="3.00" />
            <linea cantidad="1" articulo_ref="B003" importe="2.00" />
        </lineas>
        <resumen forma_de_pago="Efectivo" total="8.00" />
    </ticket>

</tickets>
